version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
    - "alixedi"
    - "currycoder"
    - "elcct"
    - "sekharpanja"
    - "adamledwards"
    - "mcbhenwood"
    - "debitan"
    - "rachaelcodes"
    - "mforner13"
    - "cgsunkel"
    - "pipporaimondi"
